FROM node:22-alpine
WORKDIR /app
COPY ./models ./models
WORKDIR /app/wsrc-admin
COPY ./wsrc-admin/package*.json ./
RUN npm ci
RUN npm install -g @angular/cli
COPY ./wsrc-admin .
RUN npm run build:dev

EXPOSE 4200

CMD ["npm", "start"]
