FROM node:latest
WORKDIR /app
COPY ./models ./models
WORKDIR /app/wsrc-app
COPY ./wsrc-app/package*.json ./
RUN npm ci
RUN npm install -g @angular/cli
COPY ./wsrc-app .
RUN npm run build:dev

EXPOSE 4200

CMD ["npm", "start"]
